#!/bin/sh

brew bundle --file=./Brewfile --verbose

# install the `.rcrc` file first to properly configure rcm
rcup rcrc
# install remainder of dotfiles
rcup

# install lts of node via nvm
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"
nvm install --lts
# install node packages
npm install -g elm-use

# install python packages
pip3 install virtualenv virtualenvwrapper

# install atom sync package
apm install package-sync
